# Generated by Django 4.2.2 on 2023-10-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='fullName', max_length=255)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('accountid', models.IntegerField(db_column='accountId')),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
    ]
