# Generated by Django 4.2.7 on 2023-12-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('role_previlege', models.IntegerField()),
                ('package_accessibility', models.IntegerField()),
            ],
            options={
                'db_table': 'Accessibility',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmailaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('verified', models.BooleanField()),
                ('primary', models.BooleanField()),
            ],
            options={
                'db_table': 'account_emailaddress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountEmailconfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('sent', models.DateTimeField(blank=True, null=True)),
                ('key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=64, unique=True)),
            ],
            options={
                'db_table': 'account_emailconfirmation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('oauth_token', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2000, null=True)),
                ('oauth_exp', models.TextField()),
                ('activation_token', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2000, null=True)),
                ('role', models.IntegerField()),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'Accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('act_level', models.IntegerField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
            ],
            options={
                'db_table': 'Activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignedmodels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='modelName', max_length=255)),
                ('category', models.IntegerField()),
                ('assigndate', models.TextField(db_column='assignDate')),
                ('currentaccuracy', models.IntegerField(blank=True, db_column='currentAccuracy', null=True)),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('is_personalized', models.BooleanField()),
            ],
            options={
                'db_table': 'AssignedModels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('codename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, unique=True)),
                ('first_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('last_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('companyname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='companyName', max_length=255)),
                ('username', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='userName', max_length=255)),
                ('password', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('ipaddress', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ipAddress', max_length=45)),
                ('rtspport', models.IntegerField(db_column='rtspPort')),
                ('channel', models.IntegerField()),
                ('deviceid', models.AutoField(db_column='deviceId', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('object_repr', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('model', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoDbLoggerStatuslog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('level', models.SmallIntegerField()),
                ('msg', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('trace', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('create_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_db_logger_statuslog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50)),
            ],
            options={
                'db_table': 'django_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000)),
                ('category', models.IntegerField()),
            ],
            options={
                'db_table': 'EMA',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Emaresponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emaid', models.IntegerField(db_column='EMAid')),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('response', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000)),
            ],
            options={
                'db_table': 'EMAResponse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('answer', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300)),
            ],
            options={
                'db_table': 'FAQ',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.IntegerField()),
                ('category', models.IntegerField()),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('log_time', models.TextField()),
            ],
            options={
                'db_table': 'Logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
            ],
            options={
                'db_table': 'Lookup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modelpackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelid', models.IntegerField(db_column='modelId')),
                ('packageid', models.IntegerField(db_column='packageId')),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'ModelPackages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='modelName', max_length=255)),
                ('category', models.IntegerField()),
                ('currentaccuracy', models.IntegerField(blank=True, db_column='currentAccuracy', null=True)),
                ('is_personalized', models.BooleanField()),
            ],
            options={
                'db_table': 'Models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificationhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seizurehistoryid', models.IntegerField(db_column='seizureHistoryid')),
                ('email', models.BooleanField()),
                ('mobile', models.BooleanField()),
                ('desktop', models.BooleanField()),
            ],
            options={
                'db_table': 'NotificationHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificationmanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('email', models.BooleanField()),
                ('mobile', models.BooleanField()),
            ],
            options={
                'db_table': 'NotificationManagement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderAccesstoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_accesstoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, unique=True)),
                ('redirect_uris', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('client_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=32)),
                ('authorization_grant_type', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=32)),
                ('client_secret', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('skip_authorization', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('algorithm', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5)),
                ('post_logout_redirect_uris', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'oauth2_provider_application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderGrant',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, unique=True)),
                ('expires', models.DateTimeField()),
                ('redirect_uri', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('scope', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('code_challenge', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('code_challenge_method', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('nonce', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('claims', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'oauth2_provider_grant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderIdtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('jti', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=32, unique=True)),
                ('expires', models.DateTimeField()),
                ('scope', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
            ],
            options={
                'db_table': 'oauth2_provider_idtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oauth2ProviderRefreshtoken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('revoked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oauth2_provider_refreshtoken',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255)),
                ('price', models.IntegerField()),
                ('discount_per', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField()),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='fullName', max_length=255)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Purchasepackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageid', models.IntegerField(db_column='packageId')),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('is_active', models.BooleanField()),
                ('purchasedate', models.TextField(db_column='PurchaseDate')),
            ],
            options={
                'db_table': 'PurchasePackages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seizurehistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountid', models.IntegerField(db_column='accountId')),
                ('filename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='fileName', max_length=255, null=True)),
                ('seizureduration', models.IntegerField(db_column='seizureDuration')),
                ('seizuretime', models.TextField(db_column='seizureTime')),
            ],
            options={
                'db_table': 'SeizureHistory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('uid', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=191)),
                ('last_login', models.DateTimeField()),
                ('date_joined', models.DateTimeField()),
                ('extra_data', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'socialaccount_socialaccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40)),
                ('client_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=191)),
                ('secret', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=191)),
                ('key', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=191)),
                ('provider_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('settings', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
            ],
            options={
                'db_table': 'socialaccount_socialapp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialappSites',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'socialaccount_socialapp_sites',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocialaccountSocialtoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('token_secret', models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socialaccount_socialtoken',
                'managed': False,
            },
        ),
    ]
