# Generated by Django 4.2.7 on 2024-02-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modeldb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alarmdevices",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "devicename",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS",
                        db_column="deviceName",
                        max_length=255,
                    ),
                ),
                (
                    "paircode",
                    models.CharField(
                        db_collation="SQL_Latin1_General_CP1_CI_AS", max_length=255
                    ),
                ),
            ],
            options={
                "db_table": "AlarmDevices",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Alarms",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("starttime", models.DateTimeField(db_column="startTime")),
                (
                    "stoptime",
                    models.DateTimeField(blank=True, db_column="stopTime", null=True),
                ),
                ("status", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "Alarms",
                "managed": False,
            },
        ),
    ]
