# Generated by Django 4.2.2 on 2023-09-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedLogs',
            fields=[
                ('pat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'generated__logs',
                'managed': False,
            },
        ),
    ]
